## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [5]:
# Type your solution here
import pandas as pd
import numpy as np

data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
Q1 = pd.DataFrame(data)
print(Q1)

Q2 = Q1[((Q1['job']=="psychologist")|(Q1['job']=="teacher"))&(Q1['num_cars']>Q1['family_size'])][['name']]
print(Q2)

Q3 = Q1[(Q1['family_size'] <= 2)&(Q1['num_cars']>=1)][['name']]
print(Q3)

Q4 = pd.Series(data["job"]).unique()
print(Q4)

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
   name
5  Lisa
    name
1  Jacob
2    Sam
4   Ryan
6    Lee
['teacher' 'psychologist' 'data scientist' 'software developer']


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [9]:
# Type your solution here
import pandas as pd
import numpy as np

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
Q2 = weights.groupby(fruit).mean()
#print(fruit)
#print(weights)
print(Q2)

0    carrot
1     apple
2    banana
3     apple
4     apple
5    carrot
6     apple
7     apple
8    banana
9    carrot
dtype: object
0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64
apple     5.200000
banana    6.000000
carrot    5.666667
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [16]:
# Type your solution here
import pandas as pd
import numpy as np

course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'], dtype=np.str)
Q3_1 = np.argsort(course_name)
print(Q3_1)
#print (course_name[Q3_1])
#print (np.sort(course_name))

IndexP = np.char.find(course_name, "P")
#print(IndexP)
Q3_2 = IndexP==0  
print (Q3_2)

[1 3 0 2 4]
[ 0 -1 -1  0 -1]
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [18]:
# Type your solution here
import pandas as pd
import numpy as np

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print(student_id)
Q4_1 = np.flipud(student_id)
print(Q4_1)

desc = np.flipud(np.sort(student_id))
Q4_2 = desc[0:3]
print(Q4_2)

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]
[6230 5241 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [27]:
# Type your solution here

# Hint: you can use arange to start off
import pandas as pd
import numpy as np

a = np.array(np.arange(0, 100, 3))
b = np.array(np.arange(0, 100, 5))
#print(a)
#print(b)
Q5 = np.union1d(a,b)
print(sum(Q5))

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [23]:
# Type your solution here
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)
Q6_1 = arr[:,[0,2,1,3]]
print(Q6_1)
Q6_2 = arr[[1,0,2], :]
print(Q6_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
